// This file will be auto-generated by Supabase CLI
// Run: pnpm supabase gen types typescript --local > src/lib/database.types.ts
// For now, we'll use a placeholder structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string
          phone: string | null
          avatar_url: string | null
          role: 'super_admin' | 'admin' | 'editor' | 'author' | 'provider' | 'user'
          status: 'active' | 'inactive' | 'suspended' | 'pending_verification'
          company_name: string | null
          rut: string | null
          bio: string | null
          website: string | null
          social_links: Json | null
          preferences: Json | null
          email_verified: boolean
          phone_verified: boolean
          created_at: string
          updated_at: string
          last_login_at: string | null
          metadata: Json | null
        }
        Insert: {
          id: string
          email: string
          full_name: string
          phone?: string | null
          avatar_url?: string | null
          role?: 'super_admin' | 'admin' | 'editor' | 'author' | 'provider' | 'user'
          status?: 'active' | 'inactive' | 'suspended' | 'pending_verification'
          company_name?: string | null
          rut?: string | null
          bio?: string | null
          website?: string | null
          social_links?: Json | null
          preferences?: Json | null
          email_verified?: boolean
          phone_verified?: boolean
          created_at?: string
          updated_at?: string
          last_login_at?: string | null
          metadata?: Json | null
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          phone?: string | null
          avatar_url?: string | null
          role?: 'super_admin' | 'admin' | 'editor' | 'author' | 'provider' | 'user'
          status?: 'active' | 'inactive' | 'suspended' | 'pending_verification'
          company_name?: string | null
          rut?: string | null
          bio?: string | null
          website?: string | null
          social_links?: Json | null
          preferences?: Json | null
          email_verified?: boolean
          phone_verified?: boolean
          created_at?: string
          updated_at?: string
          last_login_at?: string | null
          metadata?: Json | null
        }
      }
      providers: {
        Row: {
          id: string
          profile_id: string | null
          category_type: 'casas' | 'fabricantes' | 'habilitacion_servicios' | 'decoracion'
          company_name: string
          slug: string
          logo_url: string | null
          cover_image_url: string | null
          description: string | null
          description_long: string | null
          tier: 'premium' | 'destacado' | 'standard'
          status: 'draft' | 'pending_review' | 'active' | 'inactive' | 'rejected'
          email: string
          phone: string
          whatsapp: string | null
          website: string | null
          address: string | null
          city: string | null
          region: string | null
          years_experience: number | null
          certifications: Json | null
          specialties: string[] | null
          services_offered: string[] | null
          coverage_areas: string[] | null
          price_range_min: number | null
          price_range_max: number | null
          price_per_m2_min: number | null
          price_per_m2_max: number | null
          llave_en_mano: boolean
          financing_available: boolean
          features: Json | null
          gallery_images: string[] | null
          videos: string[] | null
          catalog_pdf_url: string | null
          meta_title: string | null
          meta_description: string | null
          keywords: string[] | null
          approved_by: string | null
          approved_at: string | null
          rejection_reason: string | null
          featured_until: string | null
          premium_until: string | null
          views_count: number
          clicks_count: number
          inquiries_count: number
          created_at: string
          updated_at: string
          metadata: Json | null
        }
        Insert: {
          id?: string
          profile_id?: string | null
          category_type: 'casas' | 'fabricantes' | 'habilitacion_servicios' | 'decoracion'
          company_name: string
          slug: string
          logo_url?: string | null
          cover_image_url?: string | null
          description?: string | null
          description_long?: string | null
          tier?: 'premium' | 'destacado' | 'standard'
          status?: 'draft' | 'pending_review' | 'active' | 'inactive' | 'rejected'
          email: string
          phone: string
          whatsapp?: string | null
          website?: string | null
          address?: string | null
          city?: string | null
          region?: string | null
          years_experience?: number | null
          certifications?: Json | null
          specialties?: string[] | null
          services_offered?: string[] | null
          coverage_areas?: string[] | null
          price_range_min?: number | null
          price_range_max?: number | null
          price_per_m2_min?: number | null
          price_per_m2_max?: number | null
          llave_en_mano?: boolean
          financing_available?: boolean
          features?: Json | null
          gallery_images?: string[] | null
          videos?: string[] | null
          catalog_pdf_url?: string | null
          meta_title?: string | null
          meta_description?: string | null
          keywords?: string[] | null
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          featured_until?: string | null
          premium_until?: string | null
          views_count?: number
          clicks_count?: number
          inquiries_count?: number
          created_at?: string
          updated_at?: string
          metadata?: Json | null
        }
        Update: {
          id?: string
          profile_id?: string | null
          category_type?: 'casas' | 'fabricantes' | 'habilitacion_servicios' | 'decoracion'
          company_name?: string
          slug?: string
          logo_url?: string | null
          cover_image_url?: string | null
          description?: string | null
          description_long?: string | null
          tier?: 'premium' | 'destacado' | 'standard'
          status?: 'draft' | 'pending_review' | 'active' | 'inactive' | 'rejected'
          email?: string
          phone?: string
          whatsapp?: string | null
          website?: string | null
          address?: string | null
          city?: string | null
          region?: string | null
          years_experience?: number | null
          certifications?: Json | null
          specialties?: string[] | null
          services_offered?: string[] | null
          coverage_areas?: string[] | null
          price_range_min?: number | null
          price_range_max?: number | null
          price_per_m2_min?: number | null
          price_per_m2_max?: number | null
          llave_en_mano?: boolean
          financing_available?: boolean
          features?: Json | null
          gallery_images?: string[] | null
          videos?: string[] | null
          catalog_pdf_url?: string | null
          meta_title?: string | null
          meta_description?: string | null
          keywords?: string[] | null
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          featured_until?: string | null
          premium_until?: string | null
          views_count?: number
          clicks_count?: number
          inquiries_count?: number
          created_at?: string
          updated_at?: string
          metadata?: Json | null
        }
      }
      houses: {
        Row: {
          id: string
          provider_id: string | null
          name: string
          slug: string
          model_code: string | null
          description: string | null
          description_long: string | null
          tier: 'premium' | 'destacado' | 'standard'
          status: 'draft' | 'pending_review' | 'active' | 'inactive' | 'rejected'
          topology_id: string | null
          bedrooms: number | null
          bathrooms: number | null
          area_m2: number | null
          area_built_m2: number | null
          floors: number | null
          price: number | null
          price_opportunity: number | null
          price_per_m2: number | null
          currency: string | null
          main_material: string | null
          technology_materials: string[] | null
          windows_type: string[] | null
          services_included: string[] | null
          llave_en_mano: boolean
          expandable: boolean
          mobile: boolean
          off_grid_ready: boolean
          sustainable: boolean
          smart_home: boolean
          energy_rating: string | null
          certifications: Json | null
          main_image_url: string | null
          gallery_images: string[] | null
          floor_plans: string[] | null
          videos: string[] | null
          virtual_tour_url: string | null
          brochure_pdf_url: string | null
          location_city: string | null
          location_region: string | null
          latitude: number | null
          longitude: number | null
          delivery_time_days: number | null
          assembly_time_days: number | null
          warranty_years: number | null
          meta_title: string | null
          meta_description: string | null
          keywords: string[] | null
          features: Json | null
          views_count: number
          clicks_count: number
          saves_count: number
          inquiries_count: number
          created_at: string
          updated_at: string
          metadata: Json | null
        }
        Insert: {
          id?: string
          provider_id?: string | null
          name: string
          slug: string
          model_code?: string | null
          description?: string | null
          description_long?: string | null
          tier?: 'premium' | 'destacado' | 'standard'
          status?: 'draft' | 'pending_review' | 'active' | 'inactive' | 'rejected'
          topology_id?: string | null
          bedrooms?: number | null
          bathrooms?: number | null
          area_m2?: number | null
          area_built_m2?: number | null
          floors?: number | null
          price?: number | null
          price_opportunity?: number | null
          price_per_m2?: number | null
          currency?: string | null
          main_material?: string | null
          technology_materials?: string[] | null
          windows_type?: string[] | null
          services_included?: string[] | null
          llave_en_mano?: boolean
          expandable?: boolean
          mobile?: boolean
          off_grid_ready?: boolean
          sustainable?: boolean
          smart_home?: boolean
          energy_rating?: string | null
          certifications?: Json | null
          main_image_url?: string | null
          gallery_images?: string[] | null
          floor_plans?: string[] | null
          videos?: string[] | null
          virtual_tour_url?: string | null
          brochure_pdf_url?: string | null
          location_city?: string | null
          location_region?: string | null
          latitude?: number | null
          longitude?: number | null
          delivery_time_days?: number | null
          assembly_time_days?: number | null
          warranty_years?: number | null
          meta_title?: string | null
          meta_description?: string | null
          keywords?: string[] | null
          features?: Json | null
          views_count?: number
          clicks_count?: number
          saves_count?: number
          inquiries_count?: number
          created_at?: string
          updated_at?: string
          metadata?: Json | null
        }
        Update: {
          id?: string
          provider_id?: string | null
          name?: string
          slug?: string
          model_code?: string | null
          description?: string | null
          description_long?: string | null
          tier?: 'premium' | 'destacado' | 'standard'
          status?: 'draft' | 'pending_review' | 'active' | 'inactive' | 'rejected'
          topology_id?: string | null
          bedrooms?: number | null
          bathrooms?: number | null
          area_m2?: number | null
          area_built_m2?: number | null
          floors?: number | null
          price?: number | null
          price_opportunity?: number | null
          price_per_m2?: number | null
          currency?: string | null
          main_material?: string | null
          technology_materials?: string[] | null
          windows_type?: string[] | null
          services_included?: string[] | null
          llave_en_mano?: boolean
          expandable?: boolean
          mobile?: boolean
          off_grid_ready?: boolean
          sustainable?: boolean
          smart_home?: boolean
          energy_rating?: string | null
          certifications?: Json | null
          main_image_url?: string | null
          gallery_images?: string[] | null
          floor_plans?: string[] | null
          videos?: string[] | null
          virtual_tour_url?: string | null
          brochure_pdf_url?: string | null
          location_city?: string | null
          location_region?: string | null
          latitude?: number | null
          longitude?: number | null
          delivery_time_days?: number | null
          assembly_time_days?: number | null
          warranty_years?: number | null
          meta_title?: string | null
          meta_description?: string | null
          keywords?: string[] | null
          features?: Json | null
          views_count?: number
          clicks_count?: number
          saves_count?: number
          inquiries_count?: number
          created_at?: string
          updated_at?: string
          metadata?: Json | null
        }
      }
      house_topologies: {
        Row: {
          id: string
          code: string
          bedrooms: number
          bathrooms: number
          description: string | null
          display_order: number | null
          is_active: boolean | null
        }
        Insert: {
          id?: string
          code: string
          bedrooms: number
          bathrooms: number
          description?: string | null
          display_order?: number | null
          is_active?: boolean | null
        }
        Update: {
          id?: string
          code?: string
          bedrooms?: number
          bathrooms?: number
          description?: string | null
          display_order?: number | null
          is_active?: boolean | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}